# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e97ba9735d285dde36e2f12aa7c83328b91116461ecef28d522898b6aeebaa0c3bcfb8a1f60c7be7155149eb979a567d7401c07558e48b68280db748879a269

test:
  secret_key_base: a9d8a21de6fec002ed4ec7867aa2114c998b3e89cefa0095ee5a15b02cf4d84fd223620aeb4e838b5fc4a4d76392419112e5cec384ae1b90283d67980825227d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
